workflows:
  flutter-build-ios:
    environment:
      groups:
        - my_project_secrets
      flutter: stable
      xcode: latest
      java: 17
    signing:
      xcode_project: "ios/Runner.xcodeproj"
      automatic_signing: true
      provisioning_profile_type: app_store
      entitlements: ios/Runner/Runner.entitlements
    scripts:
      - name: Clean Flutter and get dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
      - name: Build iOS IPA (Release Mode)
        script: |
          # Incrementamos el build number automáticamente para evitar el error de duplicado (ID 409)
          # Se usa 'build ipa' para asegurar que sea un binario de distribución real
          flutter build ipa --release \
            --build-number=$(($BUILD_NUMBER + 10)) \
            --export-method app-store