class CountryHelper {
  static const Map<String, String> _nameToEmoji = {
    'España': '🇪🇸',
    'Francia': '🇫🇷',
    'Italia': '🇮🇹',
    'Alemania': '🇩🇪',
    'Portugal': '🇵🇹',
    'Reino Unido': '🇬🇧',
    'Países Bajos': '🇳🇱',
    'Bélgica': '🇧🇪',
    'Suiza': '🇨🇭',
    'Austria': '🇦🇹',
    'Suecia': '🇸🇪',
    'Noruega': '🇳🇴',
    'Dinamarca': '🇩🇰',
    'Finlandia': '🇫🇮',
    'Polonia': '🇵🇱',
    'Hungría': '🇭🇺',
    'República Checa': '🇨🇿',
    'Rumanía': '🇷🇴',
    'Grecia': '🇬🇷',
    'Turquía': '🇹🇷',
    'Ucrania': '🇺🇦',
    'Croacia': '🇭🇷',
    'Serbia': '🇷🇸',
    'Bulgaria': '🇧🇬',
    'Irlanda': '🇮🇪',
    'Escocia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'Luxemburgo': '🇱🇺',
    'Mónaco': '🇲🇨',
    'Islandia': '🇮🇸',
    'Eslovenia': '🇸🇮',
    'México': '🇲🇽',
    'Estados Unidos': '🇺🇸',
    'EEUU': '🇺🇸',
    'Canadá': '🇨🇦',
    'Brasil': '🇧🇷',
    'Argentina': '🇦🇷',
    'Chile': '🇨🇱',
    'Perú': '🇵🇪',
    'Colombia': '🇨🇴',
    'Venezuela': '🇻🇪',
    'Ecuador': '🇪🇨',
    'Bolivia': '🇧🇴',
    'Paraguay': '🇵🇾',
    'Uruguay': '🇺🇾',
    'Cuba': '🇨🇺',
    'Guatemala': '🇬🇹',
    'Honduras': '🇭🇳',
    'El Salvador': '🇸🇻',
    'Nicaragua': '🇳🇮',
    'Costa Rica': '🇨🇷',
    'Panamá': '🇵🇦',
    'República Dominicana': '🇩🇴',
    'Jamaica': '🇯🇲',
    'Trinidad y Tobago': '🇹🇹',
    'Guyana': '🇬🇾',
    'Surinam': '🇸🇷',
    'Japón': '🇯🇵',
    'China': '🇨🇳',
    'Corea del Sur': '🇰🇷',
    'India': '🇮🇳',
    'Indonesia': '🇮🇩',
    'Tailandia': '🇹🇭',
    'Vietnam': '🇻🇳',
    'Filipinas': '🇵🇭',
    'Malasia': '🇲🇾',
    'Singapur': '🇸🇬',
    'Pakistán': '🇵🇰',
    'Bangladesh': '🇧🇩',
    'Irán': '🇮🇷',
    'Iraq': '🇮🇶',
    'Arabia Saudita': '🇸🇦',
    'Israel': '🇮🇱',
    'Jordania': '🇯🇴',
    'Emiratos Árabes Unidos': '🇦🇪',
    'EAU': '🇦🇪',
    'Afganistán': '🇦🇫',
    'Nepal': '🇳🇵',
    'Sri Lanka': '🇱🇰',
    'Myanmar': '🇲🇲',
    'Camboya': '🇰🇭',
    'Mongolia': '🇲🇳',
    'Egipto': '🇪🇬',
    'Sudáfrica': '🇿🇦',
    'Nigeria': '🇳🇬',
    'Kenia': '🇰🇪',
    'Etiopía': '🇪🇹',
    'Ghana': '🇬🇭',
    'Marruecos': '🇲🇦',
    'Argelia': '🇩🇿',
    'Túnez': '🇹🇳',
    'Senegal': '🇸🇳',
    'Tanzania': '🇹🇿',
    'Uganda': '🇺🇬',
    'Zimbabue': '🇿🇼',
    'Angola': '🇦🇴',
    'Mozambique': '🇲🇿',
    'Australia': '🇦🇺',
    'Nueva Zelanda': '🇳🇿',
    'Papúa Nueva Guinea': '🇵🇬',
    'Federación Rusa': '🇷🇺',
    'Russia': '🇷🇺',
    'Rusia': '🇷🇺',
  };

  static String getEmoji(String countryName) {
    if (countryName.isEmpty) return '🌍';
    
    // Búsqueda robusta: trim y case-insensitive
    final searchName = countryName.trim().toLowerCase();
    
    for (var entry in _nameToEmoji.entries) {
      if (entry.key.toLowerCase() == searchName) {
        return entry.value;
      }
    }
    
    return '🌍';
  }
}
